services:
  xcron-app:
    container_name: xcronapp
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/xcron/Dockerfile
    networks:
      - xcron_db_network
      - xcron_web_network
    volumes:
      - xcronvol:/code
  llama:
    container_name: xcronllama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - xrcon_llama_vol:/root/.ollama
    entrypoint: ["sh", "-c", "ollama serve & wait & ollama pull llama3.2 & wait & echo 'Finished!' & wait"]
    networks:
      - xcron_db_network
    #build:
    #  context: .
    #  dockerfile: ./dockerfiles/llama/Dockerfile
    #networks:
    #  - xcron_db_network
    #restart: on-failure
    #volumes:
    #  - llamamodels:/models
    #  - llamaapi:/api
  db:
    container_name: xcronpostgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - xcron_db_network
networks:
  xcron_db_network:
    driver: bridge
  xcron_web_network:
    driver: bridge
volumes:
  xcronvol:
  xrcon_llama_vol:
  #llamamodels:
  #llamaapi:
  postgresvolume: